# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Quality Check Master and Publish

on:
  push:
    branches: [ main ]

jobs:
  check-and-publish:
    name: "Quality Check Master and Publish"
    runs-on: ubuntu-latest
    if: github.actor != 'actions-user'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Checkout source code"
        uses: actions/checkout@v2
        # with:
        #   persist-credentials: false
      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: "Install node_modules"
        run: npm ci
      - name: "Build package"
        run: npm run build
      - name: "Run test"
        run: npm test
      - name: "Run lint"
        run: npm run lint
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: "Increase path version"
        run: "npm version patch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
